// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfcwhqqlyntepdycsfhc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmY3docXFseW50ZXBkeWNzZmhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMzY4NzYsImV4cCI6MjA2OTkxMjg3Nn0.OJ8OeKedZ1_FuWDQjPFvtDkVbQOd8Ks5PJshQVRjQMU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});